// Global using directives

global using System;
global using System.Collections.Generic;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Net;
global using System.Net.Http;
global using System.Net.Sockets;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using Bogus;
global using Bogus.Extensions;
global using Bogus.Extensions.Extras;
global using Bogus.Extensions.UnitedStates;
global using Cross.WebHost.AvailabilityCheck.UnitTests.Common;
global using FluentAssertions;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using Moq;
global using NUnit.Framework;
